# Generated by Django 5.2.4 on 2025-07-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
