# Generated by Django 5.2.4 on 2025-07-26 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mentions',
            field=models.ManyToManyField(related_name='mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
