# Generated by Django 5.2.4 on 2025-07-28 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentversion',
            options={},
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='version_number',
        ),
        migrations.AddField(
            model_name='documentversion',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
