# Generated by Django 5.2.4 on 2025-07-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_documentversion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
    ]
